SET(can_run_int_test YES)

EXECUTE_PROCESS(COMMAND sh -c "php -i | grep gearman.*enabled" RESULT_VARIABLE grep_rv OUTPUT_QUIET ERROR_QUIET)

IF(${grep_rv} EQUAL 0)
  FOREACH(prog bash gearmand php)
    UNSET(prog_path CACHE)
    FIND_PROGRAM(prog_path ${prog})
    IF(NOT prog_path)
      SET(can_run_int_test NO)
      BREAK()
    ENDIF()
  ENDFOREACH()
ELSE()
  SET(can_run_int_test NO)
ENDIF()

IF(${can_run_int_test})
  ADD_TEST(IntegrationTest ./tests/integration.sh)
ENDIF()
