find_package(CURL REQUIRED)
include_directories(${CURL_INCLUDE_DIR})
LIST(APPEND DRIVESHAFT_LINK_LIBRARIES curl)

INCLUDE(CheckSymbolExists)
CHECK_SYMBOL_EXISTS(CURLOPT_TCP_KEEPALIVE curl.h HAVE_CURLOPT_TCP_KEEPALIVE)
